import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/homepage/Header";
import Providers from "@/components/Providers";
import { ToastProvider } from "@/components/ToastProvider";
import MainBottomNav from "@/components/parts/MainBottomNav";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Budget Buddy | Budget Buddy Iligan City",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${inter.className} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Providers>
                    <ToastProvider>
                        <Header />
                        <main className="h-[calc(100vh-62px)] overflow-y-auto dark:bg-gray-800">{children}</main>
                        <MainBottomNav />
                    </ToastProvider>
                </Providers>
            </body>
        </html>
    );
}
